# Generated by Django 5.1.4 on 2025-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_operationlog_exec_time_operationlog_request_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellabelfield',
            name='align',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='对齐方式'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='form_grid',
            field=models.IntegerField(blank=True, null=True, verbose_name='表单栅格宽度'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='form_is_batch_edit',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否可批量编辑'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='form_is_filter',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否可筛选'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='form_is_search',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否可搜索'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='form_placehold',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='表单占位文本'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='form_rules',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='表单验证规则'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='form_visible',
            field=models.BooleanField(blank=True, null=True, verbose_name='表单是否可见'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='table_merge',
            field=models.BooleanField(blank=True, null=True, verbose_name='表格是否合并'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='table_sortable',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='表格排序方式'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='table_visible',
            field=models.BooleanField(blank=True, null=True, verbose_name='表格是否可见'),
        ),
        migrations.AddField(
            model_name='modellabelfield',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽度'),
        ),
    ]
