# Generated by Django 5.1.4 on 2025-01-20 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_modellabelfield_align_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSeparationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('model_name', models.CharField(max_length=128, verbose_name='数据模型名称')),
                ('name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('label', models.CharField(max_length=128, verbose_name='标题')),
                ('label_visible', models.BooleanField(default=True, verbose_name='显示标题')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('style', models.CharField(blank=True, max_length=128, null=True, verbose_name='样式')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='配色')),
                ('label_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='标题配色')),
                ('field_auth', models.CharField(blank=True, max_length=128, null=True, verbose_name='字段权限')),
                ('form_grid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='字段宽度')),
                ('table_show', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='显示排序')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': '模型分隔字段',
                'verbose_name_plural': '模型分隔字段',
                'ordering': ('table_show',),
                'unique_together': {('model_name', 'name')},
            },
        ),
    ]
