# Generated by Django 5.1.4 on 2025-01-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_modelseparationfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelseparationfield',
            options={'ordering': ('table_show',), 'verbose_name': 'Model separation field', 'verbose_name_plural': 'Model separation field'},
        ),
    ]
