# Generated by Django 5.1.4 on 2025-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_modellabelfieldextension_field_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelseparationfield',
            options={'ordering': ('-created_time',), 'verbose_name': 'Model separation field', 'verbose_name_plural': 'Model separation field'},
        ),
        migrations.RemoveField(
            model_name='modelseparationfield',
            name='table_show',
        ),
        migrations.AddField(
            model_name='modelseparationfield',
            name='field_sort_order',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
