# Generated by Django 5.1.4 on 2025-01-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_modelseparationfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellabelfieldextension',
            name='field_read_only',
            field=models.BooleanField(default=False, verbose_name='字段是否只读'),
        ),
        migrations.AddField(
            model_name='modelseparationfield',
            name='field_read_only',
            field=models.BooleanField(default=False, verbose_name='字段是否只读'),
        ),
    ]
