# Generated by Django 5.1.4 on 2025-02-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_modellabelfieldextension_field_read_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelseparationfield',
            name='field_sort_order',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='排序'),
        ),
    ]
