# Generated by Django 5.1.4 on 2025-01-16 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0004_remove_modellabelfield_align_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('company_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Company ID')),
                ('organizer', models.CharField(blank=True, max_length=256, null=True, verbose_name='Organizer')),
                ('name', models.CharField(max_length=256, verbose_name='Project Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Project Code')),
                ('ets_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ETS Code')),
                ('manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manager')),
                ('manager_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Manager Email')),
                ('undertaker', models.CharField(blank=True, max_length=50, null=True, verbose_name='Undertaker')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Completed'), (3, 'Archived')], default=0, verbose_name='Status')),
                ('push_time', models.DateTimeField(blank=True, null=True, verbose_name='Push Time')),
                ('agreement_template', models.IntegerField(blank=True, null=True, verbose_name='Agreement Template')),
                ('project_encode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Encode')),
                ('program_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Program Code')),
                ('program_encode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Program Encode')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('is_examinees_shown', models.BooleanField(default=False, verbose_name='Show Examinees')),
                ('set_book', models.IntegerField(blank=True, null=True, verbose_name='Set Book')),
                ('bill_calc_type', models.IntegerField(blank=True, null=True, verbose_name='Bill Calculation Type')),
                ('back_rate', models.IntegerField(blank=True, null=True, verbose_name='Back Rate')),
                ('sync_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Sync ID')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='ProjectBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Batch Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch Code')),
                ('ets_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ETS Code')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('exam_type', models.IntegerField(blank=True, null=True, verbose_name='Exam Type')),
                ('category', models.CharField(choices=[('test', 'Test'), ('formal', 'Formal')], default='formal', max_length=32, verbose_name='Category')),
                ('classification', models.CharField(choices=[('official', 'Official'), ('estimated', 'Estimated')], default='official', max_length=32, verbose_name='Classification')),
                ('exam_type_desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Exam Type Description')),
                ('exam_system_type_desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Exam System Type Description')),
                ('scene_type_desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Scene Type Description')),
                ('scene_type', models.CharField(blank=True, choices=[('etx', 'ETX'), ('sz', 'SZ'), ('joytest', 'Joy Test'), ('offline', 'Offline'), ('none', 'None')], max_length=50, null=True, verbose_name='Scene Type')),
                ('invigilator_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Invigilator Type')),
                ('exam_begin_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Exam Begin Date')),
                ('exam_end_date', models.DateField(blank=True, null=True, verbose_name='Exam End Date')),
                ('confirm_begin_date', models.DateField(blank=True, null=True, verbose_name='Confirm Begin Date')),
                ('confirm_end_date', models.DateField(blank=True, null=True, verbose_name='Confirm End Date')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='in_progress', max_length=50, verbose_name='Status')),
                ('demands', models.JSONField(blank=True, null=True, verbose_name='Exam Requirements')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='Tags')),
                ('sync_timestamp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sync Timestamp')),
                ('sync_allowed', models.IntegerField(default=1, verbose_name='Sync Allowed')),
                ('sync_time', models.DateTimeField(blank=True, null=True, verbose_name='Sync Time')),
                ('remote_configs', models.JSONField(blank=True, null=True, verbose_name='Remote Configs')),
                ('manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manager')),
                ('project_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Project Name')),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Code')),
                ('start_department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Start Department')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('project_department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Department')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='project_batch.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Batch',
                'verbose_name_plural': 'Project Batches',
                'ordering': ('-created_time',),
            },
        ),
    ]
