# Generated by Django 5.1.4 on 2025-01-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_batch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbatch',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
