# Generated by Django 5.1.4 on 2025-01-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_batch', '0002_remove_projectbatch_project_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbatch',
            name='online_exam_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Online Exam Rooms'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='schedule_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Schedule Count'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='total_exam_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Exam Rooms'),
        ),
    ]
