# Generated by Django 5.1.4 on 2025-01-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_batch', '0004_remove_desc_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbatch',
            name='exam_system_type_desc',
        ),
        migrations.RemoveField(
            model_name='projectbatch',
            name='exam_type_desc',
        ),
        migrations.RemoveField(
            model_name='projectbatch',
            name='scene_type_desc',
        ),
    ]
