# Generated by Django 5.1.4 on 2025-01-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_batch', '0005_remove_projectbatch_exam_system_type_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbatch',
            name='enable_ai_monitoring',
            field=models.BooleanField(default=False, verbose_name='Enable AI Monitoring'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='show_ata_watermark',
            field=models.BooleanField(default=False, verbose_name='Show ATA Watermark'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='stream_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stream End Time'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='stream_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stream Start Time'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='video_display_text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Video Display Text'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='videos_per_room',
            field=models.IntegerField(blank=True, null=True, verbose_name='Videos Per Room'),
        ),
    ]
