# Generated by Django 5.1.4 on 2025-01-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_batch', '0006_projectbatch_enable_ai_monitoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbatch',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Department'),
        ),
        migrations.AlterField(
            model_name='projectbatch',
            name='scene_type',
            field=models.CharField(blank=True, choices=[('etx', 'ETX'), ('sz', 'SZ'), ('joytest', 'Joy Test'), ('offline', 'Offline Arrangement'), ('none', 'None')], max_length=50, null=True, verbose_name='Scene Type'),
        ),
    ]
