# Generated by Django 5.1.4 on 2025-02-08 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0011_alter_modelseparationfield_field_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('code', models.CharField(max_length=128, verbose_name='Region Code')),
                ('name', models.CharField(max_length=128, verbose_name='Region Name')),
                ('full_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Full Name')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Country'), (2, 'Province'), (3, 'City'), (4, 'District')], null=True, verbose_name='Region Type')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Sort Order')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=20, verbose_name='Status')),
                ('tree_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tree Code')),
                ('is_capital', models.BooleanField(blank=True, null=True, verbose_name='Is Capital')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='region.region', verbose_name='Parent Region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('sort_order', 'created_time'),
                'indexes': [models.Index(fields=['parent', 'id'], name='region_regi_parent__71e2e8_idx'), models.Index(fields=['name', 'type'], name='region_regi_name_3a975a_idx')],
            },
        ),
    ]
