# Generated by Django 5.1.4 on 2025-01-09 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
        ('system', '0002_operationlog_exec_time_operationlog_request_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending_confirmation', '待入库'), ('confirmed', '已入库')], default='pending_confirmation', max_length=36, verbose_name='状态')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('type', models.CharField(choices=[('initial', '期初入库'), ('purchase', '采购入库'), ('transfer', '调拨入库'), ('profit', '盘盈入库'), ('other', '其他')], default='other', max_length=36, verbose_name='类型')),
                ('receiving_warehouse_name', models.CharField(max_length=255, verbose_name='收货仓库名称')),
                ('receiving_warehouse_code', models.CharField(max_length=100, verbose_name='收货仓库编码')),
                ('external_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='外部编码')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': '入库',
                'verbose_name_plural': '入库',
            },
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('arrival_quantity', models.IntegerField(blank=True, null=True, verbose_name='到货数量')),
                ('defect_quantity', models.IntegerField(blank=True, null=True, verbose_name='不合格品数量')),
                ('external_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='外部标识')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data ownership department')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demo.receiving', verbose_name='入库')),
            ],
            options={
                'verbose_name': '入库明细',
                'verbose_name_plural': '入库明细',
            },
        ),
    ]
